name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  - name: Set up settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          mirrors: '[{"id": "insecure-repo", "name": "httpImageJ", "mirrorOf": "http://maven.imagej.net/content/groups/public", "url": "mirrorUrl"}]'
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

